config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'application#home'

  get 'predict' => "application#predict"
  post 'predict' => "application#result"
  get 'load_products' => 'products#load_collection'
  get 'load_categories' => 'application#load_categories'
  post 'products/:id/select' => 'products#select'
  post 'products/:id/remove' => 'products#remove'
  post 'result' => "application#result"

  resources :users, only: [:update, :edit] do
    get :profile, on: :collection
  end

  get 'beer' => 'beer#index'

  namespace :api do
    resources :products, only: :index
  end

end

app/models/activnost.rb
class Activnost < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/kategory.rb
class Kategory < ActiveRecord::Base
	has_many :products
	mount_uploader :picture, CategoryPictureUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
	paginates_per 50

  belongs_to :kategory

  mount_uploader :picture, ProductPictureUploader

  scope :by_category, ->(category_id){ where kategory_id: category_id }

end

app/models/racion.rb
class Racion < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, :confirmable

	mount_uploader :avatar, UserAvatarUploader

  def age
  	Date.today.year - birthday.year
  end
  
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController
	
	def index
		@category_id = params[:category_id]
  	@products = Product.by_category(params[:category_id]).where("title ILIKE '#{params[:title]}%'").limit(10)
  	render json: @products
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def home	
  end

  def result
    use_case = Calculate::Result.new(current_user.id, params[:height][0].to_f, params[:weight][0].to_f, params[:activnost_id][:id], session[:selected_products_ids])
    @result = use_case.run
  end

  def predict
  	session[:selected_products_ids] = []
  	load_categories
  end

  def load_categories
  	@categories = Kategory.all
  end

  def beer
    
  end

end

app/controllers/beer_controller.rb
class BeerController < ApplicationController
	
	def index
	end

	def result
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
	before_filter :find_product, only: [:select, :remove]

	def select
		session[:selected_products_ids] = [] if !session[:selected_products_ids].is_a? Array
		session[:selected_products_ids] << @product.id
		session[:selected_products_ids] = session[:selected_products_ids].uniq
		@products = Product.where id: session[:selected_products_ids]
	end

	def remove
		session[:selected_products_ids] = session[:selected_products_ids] - [@product.id]
		@products = Product.where id: session[:selected_products_ids]
	end

  def load_collection
  	@category_id = params[:category_id]
  	@products = Product.page(params[:page]).per(8).by_category(params[:category_id])
  end

private

	def find_product
		@product = Product.find params[:id]
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	respond_to :html, :json
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  respond_to :html, :json
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def profile
	end

	def update
		current_user.update permitted_params
		redirect_to profile_users_path
	end

	def edit
	end

private

	def permitted_params
		params.require(:user).permit!
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<%= content_for :video do %>
		<div class="div_video_main">
	<div class="video_overley"></div>
	<div class="text_video_main">
		<h1>Personal food assistant<br></h1>
		<p>* * * * * * * * * * * * * * * * * * * * * * *</p>
		<p>Существует множество диет, которые приводят к успешному снижению веса, если Вы точно следуете предписанным правилам. Однако диеты, приводящие к снижению веса, нельзя приравнивать к здоровому питанию. Диета – это строгие ограничения, ради которых Вы вынуждены изменить модель своего питания.Вместо того чтобы тратить время на выбор таких диет, подумайте о своем здоровье и образе жизни. И в этом мы вам поможем!</p>
	</div>
		<video autoplay loop>
		<source src="/20 сладких мгновений для тех, кто обожает еду.mp4" type="video/mp4" class="video_main">
		</video>
	</div>
<% end -%>
<!-- 
<div class="row">
	<div class="col-md-4 col-md-offset-4">
	
		<% if user_signed_in? %>
			<br>
			<%= form_tag result_path do %>
				<div class="form-group">
					<%= label_tag :height %>
					<%= text_field_tag :height, nil, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= label_tag :weight %>
					<%= text_field_tag :weight, nil, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= label_tag :weight %>
					<%= collection_select :activnost_id, :id, Activnost.all, :id, :title, {},{class: "form-control"} %>
				</div>
				<div class="form-group">
				
					<%= collection_check_boxes :product, :id, Product.first(50), :id, :title do |b| %>
					<div>
						<%= b.label {b.check_box + b.text } %>
					</div>
				<% end -%>
				</div>
				<div class="form-group text-center">
					<%= submit_tag "Отправить форму", class: "btn btn-default" %>
				</div>

			<% end %>




		<% else %>
			
		<% end %>
	</div> -->
</div>



<%= render 'shared/cat', text: "Здравствуйте, Людмила Владимировна и Лина Михайловна!", font_size: 17 %>

app/views/application/load_categories.js.erb
$(".collection").html("<%= j render 'shared/categories_list', categories: @categories %>");

app/views/application/predict.html.erb
<%= content_for :video do %>
	<div class="img-header predict"></div>
<% end %>
<br><br>


<h1>Этап 1. Выберите продукты:</h1>

<div class="products collection">
	<%= render 'shared/categories_list', categories: @categories %>
</div>

<h1>Выбранные продукты:</h1>
<div class="products selected_products"></div>

<h1>Дополнительные параметры:</h1>
<div>
	<%= form_tag do %>
		<div class="form-group">
			<label>Ваш вес:</label>
			<%= text_field :weight, nil, class: "form-control" %>
		</div>

		<div class="form-group">
			<label>Ваш рост:</label>
			<%= text_field :height, nil, class: "form-control" %>
		</div>

		<div class="form-group">
			<label>Ваша дневная активность:</label>
			<%= collection_select :activnost_id, :id, Activnost.all, :id, :title, {},{class: "form-control"} %>
		</div>

		<div class="form-group">
			<%= submit_tag "Отправить", class: "btn btn-primary" %>
		</div>
	<% end %>
</div>

<div class="margin-block"></div>

<%= render 'shared/cat', text: "Выберите продукты, которыми вы питаетесь и нажмите кнопку 'Отправить'", font_size: 17 %>

app/views/application/result.html.erb
<%= content_for :video do %>
	<div class="img-header"></div>
<% end %>
<br><br>

<table class="table">
	<thead>
		<th>Продукт</th>
		<th class="text-center">Кол-во, г</th>
		<th class="text-center">Жиров, г</th>
		<th class="text-center">Белков, г</th>
		<th class="text-center">Углеводов, г</th>
		<th class="text-right">Калорийность, Ккал</th>
	</thead>
	<tbody>
		<% @result[:products].each do |product, gm| %>
			<tr>
				<td>
					<%= image_tag product.picture, size: "40x40" %>
					<%= product.title %>
				</td>
				<td class="text-center">
					<%= gm.round(2) %>
				</td>
				<td class="text-center">
					<%= (product.zhiri * gm / 100.0).round(2) %>
				</td>
				<td class="text-center">
					<%= (product.belki * gm / 100.0).round(2) %>
				</td>
				<td class="text-center">
					<%= (product.uglevodi * gm / 100.0).round(2) %>
				</td>
				<td class="text-right">
					<%= (product.calorynost * gm / 100.0).round(2) %>
				</td>
			</tr>
		<% end %>
	</tbody>
	<tfoot>
		<tr>
			<th>СУММА:</th>
			<th class="text-center"><%= @result[:gm].round(2) %></th>
			<th class="text-center"><%= @result[:zhiri].round(2) %></th>
			<th class="text-center"><%= @result[:belki].round(2) %></th>
			<th class="text-center"><%= @result[:uglevodi].round(2) %></th>
			<th class="text-right"><%= @result[:metabolizm].round(2) %></th>
		</tr>
	</tfoot>
</table>

<br><br>

<%= render 'shared/cat', text: "Похоже, сегодня вам не придется думать какие продукты нужно купить в магазине..", font_size: 16 %>

app/views/beer/index.html.erb
<%= content_for :video do %>
	<div class="img-header beer">
		<span>Узнай какой у тебя будет живот</span>
	</div>
<% end %>
<br><br>

<h1>Расчет 'Пивного животика' (только для мужщин)</h1>
	
<div class="hidden">
	<%= text_field_tag :beer_type, nil, id: "beer-type" %>
	<%= text_field_tag :chastota, nil, id: "beer-chastota" %>
	<%= text_field_tag :chastota, nil, id: "beer-count" %>
	<%= text_field_tag :zakuska, nil, id: "beer-zakuska" %>
</div>

<h3>Шаг 1</h3>
<div class="row">
	<div class="col-md-6">
		<div class="beer-choice light radio" onclick="Beer.setBeerValue('type', 'light', this)">
			<div class="background"></div>
			<div class="overlay"></div>

			<div class="wrap">
				<div id="check-part-1" class="check-sign"></div>
				<div id="check-part-2" class="check-sign"></div>
			</div>

			<span>Светлое пиво</span>
		</div>
	</div>

	<div class="col-md-6">
		<div class="beer-choice dark radio" onclick="Beer.setBeerValue('type', 'dark', this)">
			<div class="background"></div>
			<div class="overlay"></div>

			<div class="wrap">
				<div id="check-part-1" class="check-sign"></div>
				<div id="check-part-2" class="check-sign"></div>
			</div>

			<span>Темное пиво</span>
		</div>
	</div>
</div>

<h3>Шаг 2</h3>
<div class="row">
	<div class="col-md-4">
		<div class="beer-choice radio light-1raz" onclick="Beer.setBeerValue('chastota', 1, this)">
			<div class="background"></div>
			<div class="overlay"></div>

			<div class="wrap">
				<div id="check-part-1" class="check-sign"></div>
				<div id="check-part-2" class="check-sign"></div>
			</div>

			<span>1 раз в месяц</span>	
		</div>
	</div>

	<div class="col-md-4">
		<div class="beer-choice radio light-2raz" onclick="Beer.setBeerValue('chastota', 4, this)">
			<div class="background"></div>
			<div class="overlay"></div>

			<div class="wrap">
				<div id="check-part-1" class="check-sign"></div>
				<div id="check-part-2" class="check-sign"></div>
			</div>

			<span>1 раз в неделю</span>	
		</div>
	</div>

	<div class="col-md-4">
		<div class="beer-choice radio light-3raz" onclick="Beer.setBeerValue('chastota', 30, this)">
			<div class="background"></div>
			<div class="overlay"></div>

			<div class="wrap">
				<div id="check-part-1" class="check-sign"></div>
				<div id="check-part-2" class="check-sign"></div>
			</div>

			<span>Каждый день</span>
		</div>
	</div>
</div>

<h3>Шаг 3</h3>
<div class="row">
	<div class="col-md-4">
		<div class="beer-choice radio light-1" onclick="Beer.setBeerValue('count', 0.5, this)">
			<div class="background"></div>
			<div class="overlay"></div>

			<div class="wrap">
				<div id="check-part-1" class="check-sign"></div>
				<div id="check-part-2" class="check-sign"></div>
			</div>

			<span>1-2 литра</span>	
		</div>
	</div>

	<div class="col-md-4">
		<div class="beer-choice radio light-2" onclick="Beer.setBeerValue('count', 2, this)">
			<div class="background"></div>
			<div class="overlay"></div>

			<div class="wrap">
				<div id="check-part-1" class="check-sign"></div>
				<div id="check-part-2" class="check-sign"></div>
			</div>

			<span>3-4 литра</span>	
		</div>
	</div>

	<div class="col-md-4">
		<div class="beer-choice radio light-3" onclick="Beer.setBeerValue('count', 4, this)">
			<div class="background"></div>
			<div class="overlay"></div>

			<div class="wrap">
				<div id="check-part-1" class="check-sign"></div>
				<div id="check-part-2" class="check-sign"></div>
			</div>

			<span>Пока деньги не закончатся<br>(5 >)</span>
		</div>
	</div>
</div>

<h3>Шаг 4</h3>
<div class="row">
	<div class="col-md-4">
		<div class="beer-choice fish" onclick="Beer.addBeerValue('zakuska', 0, this)">
			<div class="background"></div>
			<div class="overlay"></div>

			<div class="wrap">
				<div id="check-part-1" class="check-sign"></div>
				<div id="check-part-2" class="check-sign"></div>
			</div>

			<span>Рыба</span>	
		</div>
	</div>

	<div class="col-md-4">
		<div class="beer-choice chipsi" onclick="Beer.addBeerValue('zakuska', 1, this)">
			<div class="background"></div>
			<div class="overlay"></div>

			<div class="wrap">
				<div id="check-part-1" class="check-sign"></div>
				<div id="check-part-2" class="check-sign"></div>
			</div>

			<span>Чипсы</span>	
		</div>
	</div>

	<div class="col-md-4">
		<div class="beer-choice myaso" onclick="Beer.addBeerValue('zakuska', 2, this)">
			<div class="background"></div>
			<div class="overlay"></div>

			<div class="wrap">
				<div id="check-part-1" class="check-sign"></div>
				<div id="check-part-2" class="check-sign"></div>
			</div>

			<span>Мясной сет</span>
		</div>
	</div>
</div>

<button onclick="Beer.calculate()" class="btn btn-primary" style="margin-bottom: 50px;">Рассчитать</button>


<div>
	<table class="table table-bordered">
		<tr>
			<th class="text-center" style="white-space: nowrap; width: 450px;">Ваш результат</th>
			<th class="text-center">Через</th>
			<th class="text-center">Ваш внешний вид</th>
		</tr>
		<tr>
			<td>
				<h3 class="text-center"><span id="k">0.0</span>ККал</h3>
			</td>
			<td class="text-center" style="width: 520px">
				<h3><span id="years">0</span> лет (года)</h3>
			</td>
			<td class="text-right"><img src="/beer/1.jpg" class="beer-image"></td>
		</tr>
	</table>
</div>

<%= render 'shared/cat', text: "Лучше не пейте пиво!", font_size: 27 %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expended="false">
				<span class="sr-only">
					Navigator
				</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
		</button>
			<%= link_to "HealthyFOOD", root_path, class: "navbar-brand logo" %>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Расчеты <span class="caret"></span></a>

					<ul class="dropdown-menu">
            <li><%= link_to "Суточный рацион", predict_path %></li>
            <li><%= link_to "Пивной животик", beer_path %></li>
          </ul>

				</li>

				<li><%=	link_to "Мой профиль", profile_users_path %></li>
				<li><%=	link_to "Выйти", destroy_user_session_path, method: "delete" %></li>
			<% else %>
				<li><%= link_to "Sign up", "#sign_up", "data-toggle" => "modal", :class => 'btn btn-small' %></li>
				<li><%= link_to "Sign in", "#sign_in", "data-toggle" => "modal", :class => 'btn btn-small' %></li>
			<% end %>
			</ul>
		</div>
	</div>
</nav>


<%= render 'shared/sign_in' %>
<%= render 'shared/sign_up' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MMIO_RybalkoMarina</title>
  <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,300&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/menu"%>

<%= yield :video %>

<div class="container">
	<%= yield %>
</div>
<%= render "shared/footer" %>

</body>
</html>

app/views/products/load_collection.js.erb
$(".collection").html("<%= j render 'shared/products_list', products: @products, show_pagination: true, include_typeahead: true %>");

var bestPictures = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  remote: {
    url: '/api/products?category_id=<%= params[:category_id] %>&title=%QUERY',
    wildcard: '%QUERY'
  }
});

$('#remote .typeahead').typeahead(null, {
  name: 'best-pictures',
  display: 'title',
  source: bestPictures
});

$('#remote .typeahead').on('typeahead:selected', function (e, datum) {
  Product.select(datum.id);
  setTimeout(function() {
  	$('#remote .typeahead').val("");
  }, 1);

  return datum;
});

app/views/products/remove.js.erb
$(".selected_products").html("<%= j render 'shared/products_list', products: @products, show_pagination: false, include_typeahead: false %>");
$("[data-product-id=<%= @product.id %>]").addClass('not-selected').removeClass('selected');

app/views/products/select.js.erb
$(".selected_products").html("<%= j render 'shared/products_list', products: @products, show_pagination: false, include_typeahead: false %>");
$("[data-product-id=<%= @product.id %>]").removeClass('not-selected').addClass('selected');

app/views/shared/_cat.html.erb
<div id="cat">  
  <div class="podskazkad">
    <div class="podskazkatext" style="font-size: <%= font_size %>px;">
      <%= raw text %>
    </div>
  </div> 
  <div class="cat-paws"></div>  
  <div class="cat-itself-wrap">  
    <div class="cat-itself">  
      <div id="cat-eye-left" class="cat-eye">  
        <div class="cat-eyeball"></div>  
      </div>  
      <div id="cat-eye-right" class="cat-eye">  
        <div class="cat-eyeball"></div>  
      </div>  
    </div>  
  </div>  
</div>

app/views/shared/_categories_list.html.erb
<div class="row">
	<% categories.each do |category| %>
		<div class="col-md-3">
			<div class="product" style="background: url(<%= category.picture %>) no-repeat 50% 50%;height: 192px;" onclick="Category.select(<%= category.to_json %>)">
				<div>
					<div><%= category.title %></div>
					<div class="info"><%= category.products.count %> продуктов</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/shared/_footer.html.erb
<footer>
	<div class="text-center footer">
		<p>Marina Rybalko &copy; 2016</p>
 	</div>
</footer>

app/views/shared/_product.html.erb
<% selected = session[:selected_products_ids].include?(product.id) %>
<% onclick = (show_arrow) ? "Product.select(#{product.id});" : "Product.remove(#{product.id});" %>

<div class="product <%= selected ? 'selected' : 'not-selected' %>" data-product-id="<%= product.id %>" style="background: url(<%= product.picture.url %>) no-repeat 50% 50%;height: 192px;" onclick="<%= onclick %>">
		<div>
			
			<div class="wrap">
				<div id="check-part-1" class="check-sign"></div>
				<div id="check-part-2" class="check-sign"></div>
			</div>

			<div class="wrap2">
				<div id="crest-part-1" class="crest-sign"></div>
				<div id="crest-part-2" class="crest-sign"></div>
			</div>

			<div><%= product.title %></div>
			<div>***</div>
			<div class="info">Белки: <%= product.belki %> г</div>
			<div class="info">Жиры: <%= product.zhiri %> г</div>
			<div class="info">Углеводы: <%= product.uglevodi %> г</div>
		</div>
	</div>
</div>

app/views/shared/_products_list.html.erb
<% if include_typeahead == true %>
	<div id="remote" style="margin-bottom: 20px;">
	  <input class="typeahead" type="text" placeholder="Введите продукт...">
	</div>
<% end %>


<div class="row">
	<% products.each do |product| %>
		<div class="col-md-3">
			<%= render 'shared/product', product: product, show_arrow: show_pagination %>
	<% end %>
</div>

<% if show_pagination %>
	<%= link_to "Выбрать категорию", '#', class: "btn btn-primary pull-right btn-black", style: "margin-top:20px;", onclick: 'Product.backToCategories(); return false;' %>
	<%= paginate products, remote: true, params: { controller: "products", action: "load_collection", category_id: @category_id } %>
<% end %>

app/views/shared/_sign_in.html.erb
<div class="modal fade" id="sign_in">
  <div class="modal-dialog">
    <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Sign in</h4>
          </div>

            <div class="modal-body">
              <div class="errors text-center"></div>
              <%= form_for(User.new, url: session_path(:user), html:{id: 'sign_in_user', :'data-type' => 'json'}, remote: true) do |f| %>
                <div class="form-group">
                  <%= f.label :email %>
                  <%= f.email_field :email, autofocus: true, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :password %>
                  <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
                </div>

              <div>
                <%= f.submit "Sign in", class: "btn btn-primary btn-black" %>
              </div>
            <% end %>
          </div>
    </div>
  </div>
</div>

app/views/shared/_sign_up.html.erb
<div class="modal fade" id="sign_up">
  <div class="modal-dialog">
    <div class="modal-content">
       
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Sign up</h4>
  </div>

  <div class="modal-body">
    <div class="errors"></div>
    <%= form_for(User.new, url: registration_path(:user), html: {id: 'sign_up_user', :'data-type' => 'json'}, remote: true) do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true, class: "form-control" %>
        <div class="errors-email text-danger"></div>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
        <div class="errors-password text-danger"></div>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
        <div class="errors-password_confirmation text-danger"></div>
      </div>

      <div><%= f.submit "Sign up", class: "btn btn-primary btn-black" %></div>
    <% end %>
  </div>
  </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for current_user, url: user_path(current_user), method: :put do |f| %>

	<div class="col-md-6">
		<table class="table">
			<tr>
				<th>First Name:</th>
				<td><%= f.text_field :first_name %></td>
			</tr>
			<tr>
				<th>Last Name:</th>
				<td><%= f.text_field :last_name %></td>
			</tr>
			<tr>
				<th>Email:</th>
				<td><%= f.text_field :email %></td>
			</tr>
			<tr>
				<th>Nickname:</th>
				<td><%= f.text_field :nick_name %></td>
			</tr>
			<tr>
				<th>Gender:</th>
				<td><%= f.text_field :gender %></td>
			</tr>
			<tr>
				<th>Birthday:</th>
				<td><%= f.text_field :birthday %></td>
			</tr>
			<tr>
				<th></th>
				<td>
					<%= f.submit_tag "Save", class: "btn btn-primary" %>
				</td>
			</tr>
		</table>
	</div>

	<div class="col-md-6 text-right">
		<%= image_tag current_user.avatar.thumb, size: "250x250" %>
		<%= f.file_field :avatar %>
	</div>

<% end %>

app/views/users/_user.html.erb
<div class="col-md-6">
	<table class="table">
		<tr>
			<th>First Name:</th>
			<td><%= current_user.first_name %></td>
		</tr>
		<tr>
			<th>Last Name:</th>
			<td><%= current_user.last_name %></td>
		</tr>
		<tr>
			<th>Email:</th>
			<td><%= current_user.email %></td>
		</tr>
		<tr>
			<th>Nickname:</th>
			<td><%= current_user.nick_name %></td>
		</tr>
		<tr>
			<th>Gender:</th>
			<td><%= current_user.gender %></td>
		</tr>
		<tr>
			<th>Birthday:</th>
			<td><%= current_user.birthday %></td>
		</tr>
	</table>
</div>

<div class="col-md-6 text-right">
	<%= image_tag current_user.avatar.thumb, size: "250x250" %>
</div>

<div style="margin-bottom: 160px;">&nbsp;</div>

app/views/users/edit.js.erb
$("#user-profile").html("<%= j render 'users/form' %>");

app/views/users/profile.html.erb
<%= content_for :video do %>
	<div class="img-header profile"></div>
<% end %>
<br><br>

<div class="row">
	<div class="col-md-6">
		<h1>
			It's my profile
			<%= link_to "Edit profile", edit_user_path(current_user), remote: true, class: "btn btn-primary pull-right" %>
		</h1>
	</div>
</div>

<div class="row" id="user-profile">
	<%= render current_user %>
</div>

<%= render 'shared/cat', text: "Вы можете изменить свои данные, нажав на кнопку 'Edit profile' вверху страницы", font_size: 16 %>

app/views/users/update.js.erb
$("#user-profile").html("<%= j render current_user %>");